#!/bin/sh
check_post-commit || exit 1

MESSAGE_FILE=$(get_msg_by_branch);
if [ -f $MESSAGE_FILE ];
then
    git commit -F $MESSAGE_FILE;
else
    echo "No Commit Message File Exist ($MESSAGE_FILE)"
fi
